version: 2

project_name: pulumi-provider-lock

before:
  hooks:
    - go test ./...

builds:
  - id: provider
    main: ./cmd/pulumi-resource-lock
    binary: pulumi-resource-lock
    ldflags:
      - -s -w
      - -X 'main.version={{ .Env.PLUGIN_VERSION }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: provider-archive
    formats: [tar.gz]
    name_template: "pulumi-resource-lock-v{{ .Env.PLUGIN_VERSION }}-{{ .Os }}-{{ .Arch }}"
    files:
      - pulumi-plugin.json
      - README.md
      - LICENSE

checksum:
  name_template: "SHA256SUMS.txt"

release:
  mode: keep-existing
  extra_files:
    - glob: ./schema.json
