// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const AuthMethod = {
    ClientSecretBasic: "client_secret_basic",
    ClientSecretPost: "client_secret_post",
    None: "none",
} as const;

export type AuthMethod = (typeof AuthMethod)[keyof typeof AuthMethod];

export const GrantType = {
    AuthorizationCode: "authorization_code",
    RefreshToken: "refresh_token",
    ClientCredentials: "client_credentials",
} as const;

export type GrantType = (typeof GrantType)[keyof typeof GrantType];

export const SocialProviderDriver = {
    Google: "google",
    GitHub: "github",
    Apple: "apple",
    OIDC: "oidc",
} as const;

export type SocialProviderDriver = (typeof SocialProviderDriver)[keyof typeof SocialProviderDriver];
