// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("lock");

/**
 * Management API access token; used for the Admin API too unless adminAccessToken is set. Mutually exclusive with client credentials.
 */
export declare const accessToken: string;
Object.defineProperty(exports, "accessToken", {
    get() {
        return __config.get("accessToken") ?? (utilities.getEnv("LOCK_ACCESS_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * Optional separate token addressed to the Admin API with realms:read and realms:write.
 */
export declare const adminAccessToken: string;
Object.defineProperty(exports, "adminAccessToken", {
    get() {
        return __config.get("adminAccessToken") ?? (utilities.getEnv("LOCK_ADMIN_ACCESS_TOKEN") || "");
    },
    enumerable: true,
});

/**
 * Master realm issuer URL, e.g. https://lock.example, without /api.
 */
export declare const baseUrl: string;
Object.defineProperty(exports, "baseUrl", {
    get() {
        return __config.get("baseUrl") ?? (utilities.getEnv("LOCK_BASE_URL") || "");
    },
    enumerable: true,
});

/**
 * Master realm OAuth client ID. Tokens are obtained lazily for each API and renewed before expiry.
 */
export declare const clientId: string;
Object.defineProperty(exports, "clientId", {
    get() {
        return __config.get("clientId") ?? (utilities.getEnv("LOCK_CLIENT_ID") || "");
    },
    enumerable: true,
});

/**
 * OAuth client secret. Grant read/write scopes for the resource types being managed: realms, clients, resources and social-providers. Each resource type obtains its own scoped token lazily.
 */
export declare const clientSecret: string;
Object.defineProperty(exports, "clientSecret", {
    get() {
        return __config.get("clientSecret") ?? (utilities.getEnv("LOCK_CLIENT_SECRET") || "");
    },
    enumerable: true,
});

/**
 * Authentication method for the provider's OAuth client: client_secret_basic (default) or client_secret_post.
 */
export declare const tokenEndpointAuthMethod: string;
Object.defineProperty(exports, "tokenEndpointAuthMethod", {
    get() {
        return __config.get("tokenEndpointAuthMethod") ?? (utilities.getEnv("LOCK_TOKEN_ENDPOINT_AUTH_METHOD") || "client_secret_basic");
    },
    enumerable: true,
});

