// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface RealmSettingsArgs {
    /**
     * Seconds an access token stays valid.
     */
    accessTokenLifetime?: pulumi.Input<number | undefined>;
    /**
     * Hosts a redirect URI may point at; `*` allows any.
     */
    allowedRedirectDomains?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * URI schemes a redirect URI may use.
     */
    allowedRedirectSchemes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Create a realm user on their first verified upstream sign-in.
     */
    autoProvision?: pulumi.Input<boolean | undefined>;
    /**
     * The second factors on offer: `totp`, `webauthn`.
     */
    challengeProviders?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Seconds a token issued to a machine client stays valid.
     */
    clientCredentialsLifetime?: pulumi.Input<number | undefined>;
    /**
     * Scopes every client is granted without asking.
     */
    defaultScopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Whether a client may register itself through RFC 7591.
     */
    dynamicRegistration?: pulumi.Input<boolean | undefined>;
    /**
     * Whether an unverified address blocks sign-in.
     */
    emailVerificationRequired?: pulumi.Input<boolean | undefined>;
    /**
     * Whether the first-party client skips the consent screen.
     */
    firstPartyTrusted?: pulumi.Input<boolean | undefined>;
    /**
     * Seconds an ID token stays valid.
     */
    idTokenLifetime?: pulumi.Input<number | undefined>;
    /**
     * Link an upstream identity to a local user with the same verified email address.
     */
    linkByVerifiedEmail?: pulumi.Input<boolean | undefined>;
    /**
     * The ways an identity may sign in: `password`, `passkey`, `social`.
     */
    loginMethods?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * When a second factor is demanded: `never`, `if_enrolled`, `always`.
     */
    mfaRequirement?: pulumi.Input<string | undefined>;
    /**
     * Scopes a client may request on top; `*` allows any of the catalog.
     */
    optionalScopes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * How many previous passwords may not be reused.
     */
    passwordHistory?: pulumi.Input<number | undefined>;
    /**
     * Days before a password must be changed; `0` never expires.
     */
    passwordMaxAgeDays?: pulumi.Input<number | undefined>;
    /**
     * Shortest password accepted.
     */
    passwordMinLength?: pulumi.Input<number | undefined>;
    /**
     * Whether a password must mix upper and lower case.
     */
    passwordMixedCase?: pulumi.Input<boolean | undefined>;
    /**
     * Whether a password must carry a digit.
     */
    passwordNumbers?: pulumi.Input<boolean | undefined>;
    /**
     * Whether a password must carry a symbol.
     */
    passwordSymbols?: pulumi.Input<boolean | undefined>;
    /**
     * Whether a password is checked against known breaches.
     */
    passwordUncompromised?: pulumi.Input<boolean | undefined>;
    /**
     * How many recovery codes an identity is issued.
     */
    recoveryCodes?: pulumi.Input<number | undefined>;
    /**
     * Seconds a refresh token stays valid.
     */
    refreshTokenLifetime?: pulumi.Input<number | undefined>;
    /**
     * Seconds a sign-in session lives at most, however often it is refreshed.
     */
    sessionAbsoluteLifetime?: pulumi.Input<number | undefined>;
    /**
     * Seconds before expiry at which a session token is refreshed early.
     */
    sessionTokenRefreshSkew?: pulumi.Input<number | undefined>;
    /**
     * Seconds a session token stays valid before it is refreshed.
     */
    sessionTokenTtl?: pulumi.Input<number | undefined>;
    /**
     * Whether the RFC 8693 token exchange grant is served.
     */
    tokenExchange?: pulumi.Input<boolean | undefined>;
    /**
     * Bytes of a generated TOTP secret.
     */
    totpSecretLength?: pulumi.Input<number | undefined>;
    /**
     * Time steps either side of now a TOTP code is accepted in.
     */
    totpWindow?: pulumi.Input<number | undefined>;
    /**
     * Client ids that skip the consent screen.
     */
    trustedClients?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface ScopeArgsArgs {
    /**
     * Human readable scope description. Omit to clear the existing description.
     */
    description?: pulumi.Input<string | undefined>;
}

export interface SocialProviderConfigArgs {
    /**
     * Upstream OAuth client ID, required for every driver.
     */
    clientId: pulumi.Input<string>;
    /**
     * Write-only Google, GitHub or OIDC secret. Required on creation. Omitted, null or blank values retain the previous secret, including in state; credentials cannot be cleared through this API.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * Required for OIDC. Omission on update retains the stored issuer.
     */
    issuer?: pulumi.Input<string | undefined>;
    /**
     * Required for Apple. Omission on update retains the stored key ID.
     */
    keyId?: pulumi.Input<string | undefined>;
    /**
     * Write-only Apple private key. Required for Apple on creation. Omitted, null or blank values retain the previous key, including in state; credentials cannot be cleared through this API.
     */
    privateKey?: pulumi.Input<string | undefined>;
    /**
     * Required for Apple. Omission on update retains the stored team ID.
     */
    teamId?: pulumi.Input<string | undefined>;
}
