// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface RealmSettings {
    /**
     * Seconds an access token stays valid.
     */
    accessTokenLifetime?: number;
    /**
     * Hosts a redirect URI may point at; `*` allows any.
     */
    allowedRedirectDomains?: string[];
    /**
     * URI schemes a redirect URI may use.
     */
    allowedRedirectSchemes?: string[];
    /**
     * Create a realm user on their first verified upstream sign-in.
     */
    autoProvision?: boolean;
    /**
     * The second factors on offer: `totp`, `webauthn`.
     */
    challengeProviders?: string[];
    /**
     * Seconds a token issued to a machine client stays valid.
     */
    clientCredentialsLifetime?: number;
    /**
     * Scopes every client is granted without asking.
     */
    defaultScopes?: string[];
    /**
     * Whether a client may register itself through RFC 7591.
     */
    dynamicRegistration?: boolean;
    /**
     * Whether an unverified address blocks sign-in.
     */
    emailVerificationRequired?: boolean;
    /**
     * Whether the first-party client skips the consent screen.
     */
    firstPartyTrusted?: boolean;
    /**
     * Seconds an ID token stays valid.
     */
    idTokenLifetime?: number;
    /**
     * Link an upstream identity to a local user with the same verified email address.
     */
    linkByVerifiedEmail?: boolean;
    /**
     * The ways an identity may sign in: `password`, `passkey`, `social`.
     */
    loginMethods?: string[];
    /**
     * When a second factor is demanded: `never`, `if_enrolled`, `always`.
     */
    mfaRequirement?: string;
    /**
     * Scopes a client may request on top; `*` allows any of the catalog.
     */
    optionalScopes?: string[];
    /**
     * How many previous passwords may not be reused.
     */
    passwordHistory?: number;
    /**
     * Days before a password must be changed; `0` never expires.
     */
    passwordMaxAgeDays?: number;
    /**
     * Shortest password accepted.
     */
    passwordMinLength?: number;
    /**
     * Whether a password must mix upper and lower case.
     */
    passwordMixedCase?: boolean;
    /**
     * Whether a password must carry a digit.
     */
    passwordNumbers?: boolean;
    /**
     * Whether a password must carry a symbol.
     */
    passwordSymbols?: boolean;
    /**
     * Whether a password is checked against known breaches.
     */
    passwordUncompromised?: boolean;
    /**
     * How many recovery codes an identity is issued.
     */
    recoveryCodes?: number;
    /**
     * Seconds a refresh token stays valid.
     */
    refreshTokenLifetime?: number;
    /**
     * Seconds a sign-in session lives at most, however often it is refreshed.
     */
    sessionAbsoluteLifetime?: number;
    /**
     * Seconds before expiry at which a session token is refreshed early.
     */
    sessionTokenRefreshSkew?: number;
    /**
     * Seconds a session token stays valid before it is refreshed.
     */
    sessionTokenTtl?: number;
    /**
     * Whether the RFC 8693 token exchange grant is served.
     */
    tokenExchange?: boolean;
    /**
     * Bytes of a generated TOTP secret.
     */
    totpSecretLength?: number;
    /**
     * Time steps either side of now a TOTP code is accepted in.
     */
    totpWindow?: number;
    /**
     * Client ids that skip the consent screen.
     */
    trustedClients?: string[];
}

export interface ScopeArgs {
    /**
     * Human readable scope description. Omit to clear the existing description.
     */
    description?: string;
}

export interface SocialProviderConfig {
    /**
     * Upstream OAuth client ID, required for every driver.
     */
    clientId: string;
    /**
     * Write-only Google, GitHub or OIDC secret. Required on creation. Omitted, null or blank values retain the previous secret, including in state; credentials cannot be cleared through this API.
     */
    clientSecret?: string;
    /**
     * Required for OIDC. Omission on update retains the stored issuer.
     */
    issuer?: string;
    /**
     * Required for Apple. Omission on update retains the stored key ID.
     */
    keyId?: string;
    /**
     * Write-only Apple private key. Required for Apple on creation. Omitted, null or blank values retain the previous key, including in state; credentials cannot be cleared through this API.
     */
    privateKey?: string;
    /**
     * Required for Apple. Omission on update retains the stored team ID.
     */
    teamId?: string;
}

