// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A realm's OAuth client. Import using realm-slug/client-id. The secret is available at creation and preserved during refresh; importing does not disclose an existing secret.
 */
export class Client extends pulumi.CustomResource {
    /**
     * Get an existing Client resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Client {
        return new Client(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lock:index:Client';

    /**
     * Returns true if the given object is an instance of Client.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Client {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Client.__pulumiType;
    }

    /**
     * Back-channel logout endpoint. Omit or set an empty string to clear it.
     */
    declare public readonly backchannelLogoutUri: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly clientId: pulumi.Output<string>;
    declare public /*out*/ readonly clientSecret: pulumi.Output<string | undefined>;
    declare public /*out*/ readonly confidential: pulumi.Output<boolean>;
    declare public readonly consentRequired: pulumi.Output<boolean>;
    declare public readonly grantTypes: pulumi.Output<enums.GrantType[]>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly postLogoutRedirectUris: pulumi.Output<string[] | undefined>;
    /**
     * Realm slug. Changing it replaces the client.
     */
    declare public readonly realm: pulumi.Output<string>;
    declare public readonly redirectUris: pulumi.Output<string[] | undefined>;
    declare public /*out*/ readonly revoked: pulumi.Output<boolean>;
    declare public /*out*/ readonly scopes: pulumi.Output<string[]>;
    /**
     * Client authentication method. Changing it replaces the client so its credentials remain consistent with Pulumi state.
     */
    declare public readonly tokenEndpointAuthMethod: pulumi.Output<enums.AuthMethod>;

    /**
     * Create a Client resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClientArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.grantTypes === undefined && !opts.urn) {
                throw new Error("Missing required property 'grantTypes'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.realm === undefined && !opts.urn) {
                throw new Error("Missing required property 'realm'");
            }
            if (args?.tokenEndpointAuthMethod === undefined && !opts.urn) {
                throw new Error("Missing required property 'tokenEndpointAuthMethod'");
            }
            resourceInputs["backchannelLogoutUri"] = args?.backchannelLogoutUri;
            resourceInputs["consentRequired"] = (args?.consentRequired) ?? true;
            resourceInputs["grantTypes"] = args?.grantTypes;
            resourceInputs["name"] = args?.name;
            resourceInputs["postLogoutRedirectUris"] = args?.postLogoutRedirectUris;
            resourceInputs["realm"] = args?.realm;
            resourceInputs["redirectUris"] = args?.redirectUris;
            resourceInputs["tokenEndpointAuthMethod"] = args?.tokenEndpointAuthMethod;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["confidential"] = undefined /*out*/;
            resourceInputs["revoked"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
        } else {
            resourceInputs["backchannelLogoutUri"] = undefined /*out*/;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["clientSecret"] = undefined /*out*/;
            resourceInputs["confidential"] = undefined /*out*/;
            resourceInputs["consentRequired"] = undefined /*out*/;
            resourceInputs["grantTypes"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["postLogoutRedirectUris"] = undefined /*out*/;
            resourceInputs["realm"] = undefined /*out*/;
            resourceInputs["redirectUris"] = undefined /*out*/;
            resourceInputs["revoked"] = undefined /*out*/;
            resourceInputs["scopes"] = undefined /*out*/;
            resourceInputs["tokenEndpointAuthMethod"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        const replaceOnChanges = { replaceOnChanges: ["realm", "tokenEndpointAuthMethod"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Client.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Client resource.
 */
export interface ClientArgs {
    /**
     * Back-channel logout endpoint. Omit or set an empty string to clear it.
     */
    backchannelLogoutUri?: pulumi.Input<string | undefined>;
    consentRequired?: pulumi.Input<boolean | undefined>;
    grantTypes: pulumi.Input<pulumi.Input<enums.GrantType>[]>;
    name: pulumi.Input<string>;
    postLogoutRedirectUris?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Realm slug. Changing it replaces the client.
     */
    realm: pulumi.Input<string>;
    redirectUris?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Client authentication method. Changing it replaces the client so its credentials remain consistent with Pulumi state.
     */
    tokenEndpointAuthMethod: pulumi.Input<enums.AuthMethod>;
}
