// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ClientArgs } from "./client";
export type Client = import("./client").Client;
export const Client: typeof import("./client").Client = null as any;
utilities.lazyLoad(exports, ["Client"], () => require("./client"));

export { ProtectedResourceArgs } from "./protectedResource";
export type ProtectedResource = import("./protectedResource").ProtectedResource;
export const ProtectedResource: typeof import("./protectedResource").ProtectedResource = null as any;
utilities.lazyLoad(exports, ["ProtectedResource"], () => require("./protectedResource"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { RealmArgs } from "./realm";
export type Realm = import("./realm").Realm;
export const Realm: typeof import("./realm").Realm = null as any;
utilities.lazyLoad(exports, ["Realm"], () => require("./realm"));

export { SocialProviderArgs } from "./socialProvider";
export type SocialProvider = import("./socialProvider").SocialProvider;
export const SocialProvider: typeof import("./socialProvider").SocialProvider = null as any;
utilities.lazyLoad(exports, ["SocialProvider"], () => require("./socialProvider"));


// Export enums:
export * from "./types/enums";

// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "lock:index:Client":
                return new Client(name, <any>undefined, { urn })
            case "lock:index:ProtectedResource":
                return new ProtectedResource(name, <any>undefined, { urn })
            case "lock:index:Realm":
                return new Realm(name, <any>undefined, { urn })
            case "lock:index:SocialProvider":
                return new SocialProvider(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("lock", "index", _module)
pulumi.runtime.registerResourcePackage("lock", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:lock") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
