// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'lock';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * Management API access token; used for the Admin API too unless adminAccessToken is set. Mutually exclusive with client credentials.
     */
    declare public readonly accessToken: pulumi.Output<string>;
    /**
     * Optional separate token addressed to the Admin API with realms:read and realms:write.
     */
    declare public readonly adminAccessToken: pulumi.Output<string>;
    /**
     * Master realm issuer URL, e.g. https://lock.example, without /api.
     */
    declare public readonly baseUrl: pulumi.Output<string>;
    /**
     * Master realm OAuth client ID. Tokens are obtained lazily for each API and renewed before expiry.
     */
    declare public readonly clientId: pulumi.Output<string>;
    /**
     * OAuth client secret. Grant read/write scopes for the resource types being managed: realms, clients, resources and social-providers. Each resource type obtains its own scoped token lazily.
     */
    declare public readonly clientSecret: pulumi.Output<string>;
    /**
     * Authentication method for the provider's OAuth client: client_secret_basic (default) or client_secret_post.
     */
    declare public readonly tokenEndpointAuthMethod: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["accessToken"] = (args?.accessToken ? pulumi.secret(args.accessToken) : undefined) ?? (utilities.getEnv("LOCK_ACCESS_TOKEN") || "");
            resourceInputs["adminAccessToken"] = (args?.adminAccessToken ? pulumi.secret(args.adminAccessToken) : undefined) ?? (utilities.getEnv("LOCK_ADMIN_ACCESS_TOKEN") || "");
            resourceInputs["baseUrl"] = (args?.baseUrl) ?? (utilities.getEnv("LOCK_BASE_URL") || "");
            resourceInputs["clientId"] = (args?.clientId) ?? (utilities.getEnv("LOCK_CLIENT_ID") || "");
            resourceInputs["clientSecret"] = (args?.clientSecret ? pulumi.secret(args.clientSecret) : undefined) ?? (utilities.getEnv("LOCK_CLIENT_SECRET") || "");
            resourceInputs["tokenEndpointAuthMethod"] = (args?.tokenEndpointAuthMethod) ?? (utilities.getEnv("LOCK_TOKEN_ENDPOINT_AUTH_METHOD") || "client_secret_basic");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["accessToken", "adminAccessToken", "clientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Management API access token; used for the Admin API too unless adminAccessToken is set. Mutually exclusive with client credentials.
     */
    accessToken?: pulumi.Input<string | undefined>;
    /**
     * Optional separate token addressed to the Admin API with realms:read and realms:write.
     */
    adminAccessToken?: pulumi.Input<string | undefined>;
    /**
     * Master realm issuer URL, e.g. https://lock.example, without /api.
     */
    baseUrl?: pulumi.Input<string | undefined>;
    /**
     * Master realm OAuth client ID. Tokens are obtained lazily for each API and renewed before expiry.
     */
    clientId?: pulumi.Input<string | undefined>;
    /**
     * OAuth client secret. Grant read/write scopes for the resource types being managed: realms, clients, resources and social-providers. Each resource type obtains its own scoped token lazily.
     */
    clientSecret?: pulumi.Input<string | undefined>;
    /**
     * Authentication method for the provider's OAuth client: client_secret_basic (default) or client_secret_post.
     */
    tokenEndpointAuthMethod?: pulumi.Input<string | undefined>;
}
