// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A Lock realm. Import using its slug. Only explicitly supplied settings are managed; omitted settings retain their server values.
 */
export class Realm extends pulumi.CustomResource {
    /**
     * Get an existing Realm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Realm {
        return new Realm(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lock:index:Realm';

    /**
     * Returns true if the given object is an instance of Realm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Realm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Realm.__pulumiType;
    }

    /**
     * Realm hostname, without a scheme or path. DNS verification status is exposed as domainStatus.
     */
    declare public readonly domain: pulumi.Output<string>;
    declare public /*out*/ readonly domainStatus: pulumi.Output<string>;
    declare public /*out*/ readonly host: pulumi.Output<string>;
    declare public /*out*/ readonly issuer: pulumi.Output<string>;
    declare public /*out*/ readonly master: pulumi.Output<boolean>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Realm policy overrides. Removing an override stops managing it and retains its server value; the API has no reset-to-default operation. Set an explicit value to change it.
     */
    declare public readonly settings: pulumi.Output<outputs.RealmSettings | undefined>;
    /**
     * Immutable realm identifier. Changing it replaces the realm and its contents.
     */
    declare public readonly slug: pulumi.Output<string>;

    /**
     * Create a Realm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RealmArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            resourceInputs["domain"] = args?.domain;
            resourceInputs["name"] = args?.name;
            resourceInputs["settings"] = args?.settings;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["domainStatus"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["issuer"] = undefined /*out*/;
            resourceInputs["master"] = undefined /*out*/;
        } else {
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["domainStatus"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["issuer"] = undefined /*out*/;
            resourceInputs["master"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["settings"] = undefined /*out*/;
            resourceInputs["slug"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["slug"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Realm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Realm resource.
 */
export interface RealmArgs {
    /**
     * Realm hostname, without a scheme or path. DNS verification status is exposed as domainStatus.
     */
    domain: pulumi.Input<string>;
    name: pulumi.Input<string>;
    /**
     * Realm policy overrides. Removing an override stops managing it and retains its server value; the API has no reset-to-default operation. Set an explicit value to change it.
     */
    settings?: pulumi.Input<inputs.RealmSettingsArgs | undefined>;
    /**
     * Immutable realm identifier. Changing it replaces the realm and its contents.
     */
    slug: pulumi.Input<string>;
}
