// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A realm social login provider. Import using realm-slug/provider-UUID. The API never returns credentials; imports cannot recover them and refresh preserves credentials already in state.
 */
export class SocialProvider extends pulumi.CustomResource {
    /**
     * Get an existing SocialProvider resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): SocialProvider {
        return new SocialProvider(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lock:index:SocialProvider';

    /**
     * Returns true if the given object is an instance of SocialProvider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SocialProvider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SocialProvider.__pulumiType;
    }

    declare public /*out*/ readonly callbackUrl: pulumi.Output<string>;
    /**
     * Driver configuration. The entire output object is secret to protect retained write-only credentials. Omitted optional values retain their stored values on update.
     */
    declare public readonly config: pulumi.Output<outputs.SocialProviderConfig>;
    /**
     * Upstream driver. Changing it replaces the provider; replacement deletes first when the realm and key are unchanged.
     */
    declare public readonly driver: pulumi.Output<enums.SocialProviderDriver>;
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * Immutable key used in login and callback URLs. Changing it replaces the provider.
     */
    declare public readonly key: pulumi.Output<string>;
    declare public /*out*/ readonly providerId: pulumi.Output<string>;
    /**
     * Realm slug. Changing it replaces the provider.
     */
    declare public readonly realm: pulumi.Output<string>;

    /**
     * Create a SocialProvider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SocialProviderArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.config === undefined && !opts.urn) {
                throw new Error("Missing required property 'config'");
            }
            if (args?.driver === undefined && !opts.urn) {
                throw new Error("Missing required property 'driver'");
            }
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.key === undefined && !opts.urn) {
                throw new Error("Missing required property 'key'");
            }
            if (args?.realm === undefined && !opts.urn) {
                throw new Error("Missing required property 'realm'");
            }
            resourceInputs["config"] = args?.config;
            resourceInputs["driver"] = args?.driver;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["key"] = args?.key;
            resourceInputs["realm"] = args?.realm;
            resourceInputs["callbackUrl"] = undefined /*out*/;
            resourceInputs["providerId"] = undefined /*out*/;
        } else {
            resourceInputs["callbackUrl"] = undefined /*out*/;
            resourceInputs["config"] = undefined /*out*/;
            resourceInputs["driver"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
            resourceInputs["providerId"] = undefined /*out*/;
            resourceInputs["realm"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["driver", "key", "realm"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(SocialProvider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a SocialProvider resource.
 */
export interface SocialProviderArgs {
    /**
     * Driver configuration. The entire output object is secret to protect retained write-only credentials. Omitted optional values retain their stored values on update.
     */
    config: pulumi.Input<inputs.SocialProviderConfigArgs>;
    /**
     * Upstream driver. Changing it replaces the provider; replacement deletes first when the realm and key are unchanged.
     */
    driver: pulumi.Input<enums.SocialProviderDriver>;
    enabled: pulumi.Input<boolean>;
    /**
     * Immutable key used in login and callback URLs. Changing it replaces the provider.
     */
    key: pulumi.Input<string>;
    /**
     * Realm slug. Changing it replaces the provider.
     */
    realm: pulumi.Input<string>;
}
